# Generated by Django 4.1.5 on 2023-12-29 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion_categoria', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='disponibilidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion_disponibilidad', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='estado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion_estado', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_producto', models.CharField(max_length=80)),
                ('precio_producto', models.IntegerField()),
                ('descripcion_producto', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TipoPublicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion_TipoPublicacion', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_usuario', models.IntegerField()),
                ('dv_usuario', models.CharField(max_length=1)),
                ('correo_usuario', models.CharField(max_length=80)),
                ('telefono_usuario', models.IntegerField()),
                ('direccion_usuario', models.CharField(max_length=150)),
                ('primer_nombre_usuario', models.CharField(max_length=80)),
                ('apellido_paterno_usuario', models.CharField(max_length=80)),
                ('apellido_materno_usuario', models.CharField(max_length=80)),
                ('nombre_fantasia_usuario', models.CharField(max_length=80)),
                ('contrasena_usuario', models.CharField(max_length=80)),
            ],
        ),
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.AddField(
            model_name='producto',
            name='TipoPublicacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='post.tipopublicacion'),
        ),
        migrations.AddField(
            model_name='producto',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='post.categoria'),
        ),
        migrations.AddField(
            model_name='producto',
            name='disponibilidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='post.disponibilidad'),
        ),
        migrations.AddField(
            model_name='producto',
            name='estado_producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='post.estado'),
        ),
    ]
