# Generated by Django 4.1.5 on 2024-01-05 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_publicacion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publicacion',
            old_name='producto',
            new_name='Producto',
        ),
        migrations.AddField(
            model_name='publicacion',
            name='estado',
            field=models.CharField(default='04/01/20214', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='publicacion',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=100000, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio_producto',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='publicacion',
            name='fecha_publicacion',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
