# Generated by Django 4.1.5 on 2024-01-05 00:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_rename_producto_publicacion_producto_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publicacion',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='publicacion',
            name='precio',
        ),
    ]
